### ISSUE TITLE
Custom folder setup

### ISSUE THREAD

**Issue by iskrisis** [afbora/kirby-loader#3]
Hi, there is some path logic that break custom folder setup.

Its https://github.com/afbora/kirby-loader/blob/eb57d3f56287e3b44713bf86335fc3406d94942c/src/Loader.php#L24 and https://github.com/afbora/kirby-loader/blob/eb57d3f56287e3b44713bf86335fc3406d94942c/src/Loader.php#L31

```
if (strpos($root, $index) === false) {
	$root = $index . DIRECTORY_SEPARATOR . ltrim($root, DIRECTORY_SEPARATOR);
}
```
I end up with `/path/to/project/public/path/to/project`.

I understand it's for automatic relative paths but its happening when using closure aswell - and there one can do this thing themselves but i cant not do it. I think it's very limiting and just omitting those three lines in closure case would really help.

**Comment by afbora** [comment]
Thank you for feedback @iskrisis . I've done few improvements on #4 Could you test please?

**Comment by iskrisis** [comment]
Confirming works correctly with closure 
```
'afbora.loader.roots' => [
	function () {
            return realpath("./../global/plugins");
        },
],
```
Much better fix then what i proposed 🙃 

Thank you!
